image:
  repository: quay.io/minio/minio
  tag: RELEASE.2025-02-07T23-21-09Z
  pullPolicy: IfNotPresent

podLabels:
  app.kubernetes.io/feature: storage-core

mode: standalone

# Match the keys in the manual secret
existingSecret: "minio-secret"
accessKeyKey: "rootUser"
secretKeyKey: "rootPassword"

service:
  type: ClusterIP
  port: 9000
  consolePort: 9001

buckets:
  - name: tempo-traces
    policy: public
    purge: false
  - name: prometheus-blocks
    policy: private
    purge: false
  - name: loki-chunks
    policy: private
    purge: false
  - name: loki-ruler
    policy: private
    purge: false
  - name: loki-admin
    policy: private
    purge: false

# Post-install Job Hardening
postJob:
  # Attempting to fix linter errors for postJob
  ttlSecondsAfterFinished: 3600
