apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-hub
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/victoriacheng15/observability-hub.git
    targetRevision: HEAD
    path: k3s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: hub
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
