# --- Namespace: hub ---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hub-automation
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hub-intelligence
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hub-sensor
automountServiceAccountToken: false

# --- Namespace: databases ---
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: db-admin

# --- Namespace: argocd ---
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-redis
automountServiceAccountToken: false

# --- Namespace: kube-system ---
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gpu-plugin

# --- Namespace: observability ---
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: thanos-query
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: thanos-storegateway
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: thanos-compactor
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tempo
automountServiceAccountToken: false
