checks:
  exclude:
    # MinIO
    - job-ttl-seconds-after-finished

    # Node Exporter
    - host-network
    - host-pid
    - sensitive-host-mounts

    # Prometheus
    - no-read-only-root-fs
    - unset-cpu-requirements
    - unset-memory-requirements

    # Postgres
    - run-as-non-root
    - pdb-unhealthy-pod-eviction-policy
