apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - overlays/dev
  - overlays/prod
  - base/hub-apps/automation.yaml
  - base/hub-apps/intelligence.yaml
  - base/rbac/cluster-rbac.yaml
  - cilium-policies/observability-stack-policy.yaml
