apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hardware-sim-lab-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/victoriacheng15/hardware-sim-lab.git
    targetRevision: main
    path: k3s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev-hardware-sim
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
