podLabels:
  app.kubernetes.io/feature: observability-ui

admin:
  existingSecret: "grafana-admin-secret"
  userKey: admin-user
  passwordKey: admin-password

persistence:
  enabled: true

initChownData:
  enabled: true

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        uid: loki-provisioned
        url: http://loki-gateway.observability.svc.cluster.local:80
        access: proxy
        isDefault: true
      - name: Tempo
        type: tempo
        uid: tempo-provisioned
        url: http://tempo.observability.svc.cluster.local:3200
        access: proxy
        jsonData:
          httpMethod: GET
          tracesToLogsV2:
            datasourceUid: 'loki-provisioned'
            groupFilterRegex: ''
            filterByTraceId: false
            filterBySpanId: false
            noResultPolicy: 'hide'
          tracesToMetrics:
            datasourceUid: 'prometheus-provisioned'
            spanAttributes: [service.name, http.status_code]
          serviceMap:
            datasourceUid: 'prometheus-provisioned'
          search:
            hide: false
          traceql:
            hide: false
          nodeGraph:
            enabled: true
          lokiSearch:
            datasourceUid: 'loki-provisioned'
      - name: Prometheus
        type: prometheus
        uid: prometheus-provisioned
        url: http://prometheus-server.observability.svc.cluster.local:80
        access: proxy
        jsonData:
          httpMethod: POST
          timeInterval: 15s
      - name: PostgreSQL
        type: postgres
        uid: postgresql-provisioned
        url: postgres-hub-rw.databases.svc.cluster.local:5432
        database: homelab
        user: server
        jsonData:
          database: homelab
          sslmode: 'disable'
          postgresVersion: 1700
        secureJsonData:
          password: ${POSTGRES_PASSWORD}

dashboardProviders: {}

service:
  type: NodePort
  port: 80
  targetPort: 3000
  nodePort: 30000

# Security settings and UI tweaks
grafana.ini:
  server:
    domain: grafana.observability-hub.home
    root_url: http://grafana.observability-hub.home:30000
  users:
    allow_sign_up: false
  analytics:
    reporting_enabled: false
  check_for_updates: false

extraVolumes:
  - name: tmp
    emptyDir: {}

extraVolumeMounts:
  - name: tmp
    mountPath: /tmp

envValueFrom:
  POSTGRES_PASSWORD:
    secretKeyRef:
      name: postgres-secret
      key: server-db-password

# Fix for grafana-test pod in manifest
testFramework:
  enabled: false
