apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - analytics/manifest.yaml
  - hardware-sim/chaos-controller.yaml
  - hardware-sim/sensor-fleet.yaml
  - rbac/serviceaccounts.yaml
  - rbac/roles.yaml
  - rbac/bindings.yaml
