podLabels:
  app.kubernetes.io/feature: database-management

env:
  email: "admin@observability-hub.home"

existingSecret: "pgadmin-secret"

secretKeys:
  pgadminPasswordKey: "password"

serverDefinitions:
  enabled: true
  servers:
    postgres-hub:
      Name: "Postgres Hub"
      Group: "Observability Hub"
      Host: "postgres-hub-rw.databases.svc.cluster.local"
      Port: 5432
      MaintenanceDB: "homelab"
      Username: "server"
      SSLMode: "prefer"

service:
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 30080

persistentVolume:
  enabled: true
  size: 1Gi
  storageClass: "local-path-retain"

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

podSecurityContext:
  fsGroup: 5050
  runAsGroup: 5050
  runAsUser: 5050

containerSecurityContext:
  readOnlyRootFilesystem: false # Required for pgAdmin to manage its internal files
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
