apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: dev-hub

images:
  - name: ghcr.io/victoriacheng15/observability-hub/analytics
    newTag: canary
