apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: hub

images:
  - name: ghcr.io/victoriacheng15/observability-hub/analytics
    newTag: sha-0c243b3
  - name: ghcr.io/victoriacheng15/observability-hub/chaos-controller
    newTag: sha-0c243b3
  - name: ghcr.io/victoriacheng15/observability-hub/sensor
    newTag: sha-0c243b3

patches:
  - target:
      kind: Deployment
      name: chaos-controller
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: hardware-sim
      - op: replace
        path: /spec/replicas
        value: 2
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: "hardware-sim"
  - target:
      kind: Deployment
      name: sensor-fleet
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: hardware-sim
      - op: replace
        path: /spec/replicas
        value: 8
  - target:
      kind: ServiceAccount
      name: hw-controller
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: hardware-sim
  - target:
      kind: ServiceAccount
      name: hw-sensor
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: hardware-sim
  - target:
      kind: Role
      name: hw-controller-role
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: hardware-sim
  - target:
      kind: RoleBinding
      name: hw-controller-binding
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: hardware-sim
