apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/hardware-sim
  - ../../base/rbac

images:
  - name: ghcr.io/victoriacheng15/observability-hub/chaos-controller
    newTag: sha-a92c34d
  - name: ghcr.io/victoriacheng15/observability-hub/mqtt-ingestor
    newTag: sha-12e1e24
  - name: ghcr.io/victoriacheng15/observability-hub/sensor
    newTag: sha-a92c34d

patches:
  # --- Simulation Fleet (hardware-sim) ---
  - target:
      kind: Deployment
      name: chaos-controller
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: hardware-sim
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: "hardware-sim"
  - target:
      kind: StatefulSet
      name: sensor-fleet
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: hardware-sim
      - op: replace
        path: /spec/replicas
        value: 3
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: "hardware-sim"
  - target:
      kind: Service
      name: sensor-fleet
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: hardware-sim
  # --- Simulation RBAC (hardware-sim) ---
  - target:
      name: hw-.*
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: hardware-sim
  - target:
      kind: RoleBinding
      name: hw-controller-binding
    patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: hardware-sim
