apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaos-controller
  namespace: hardware-sim
  labels:
    app: chaos-controller
    feature: simulation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chaos-controller
  template:
    metadata:
      labels:
        app: chaos-controller
    spec:
      serviceAccountName: hw-controller
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      imagePullSecrets:
        - name: ghcr-auth
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - chaos-controller
              topologyKey: kubernetes.io/hostname
      containers:
      - name: chaos-controller
        image: ghcr.io/victoriacheng15/observability-hub/chaos-controller
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          capabilities:
            drop:
            - ALL
        env:
        - name: MQTT_BROKER
          value: "tcp://emqx.observability.svc.cluster.local:1883"
        - name: TARGET_NAMESPACE
          value: "hardware-sim"
        resources:
          requests:
            cpu: "20m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "256Mi"
