fullnameOverride: opentelemetry

podLabels:
  app.kubernetes.io/feature: observability-otel

mode: deployment

replicaCount: 1

image:
  repository: otel/opentelemetry-collector-contrib
  tag: 0.94.0 # Using a recent stable version
  pullPolicy: IfNotPresent

# Use alternateConfig to fully control the collector's configuration and avoid default merges
alternateConfig:
  extensions:
    health_check:
      endpoint: 0.0.0.0:13133
  receivers:
    otlp:
      protocols:
        grpc: {}
        http: {}
  processors:
    batch: {}
    resource:
      attributes:
        - key: service
          action: upsert
          from_attribute: service.name
        - key: loki.resource.labels
          action: insert
          value: service
  exporters:
    otlp:
      endpoint: tempo.observability.svc.cluster.local:4317
      tls:
        insecure: true
    logging:
      loglevel: debug
    loki:
      endpoint: http://loki.observability.svc.cluster.local:3100/loki/api/v1/push
    prometheusremotewrite:
      endpoint: http://prometheus-server.observability.svc.cluster.local:80/api/v1/write
  service:
    telemetry:
      metrics:
        address: 0.0.0.0:8888
    extensions: [health_check] # Ensure health_check is used
    pipelines:
      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: [otlp]
      metrics:
        receivers: [otlp]
        processors: [batch]
        exporters: [prometheusremotewrite]
      logs:
        receivers: [otlp]
        processors: [batch, resource]
        exporters: [loki]

# Expose as LoadBalancer so host-level systemd services (e.g. proxy) can reach the collector via localhost
service:
  type: LoadBalancer

ports:
  otlp:
    enabled: true
    servicePort: 4317
    nodePort: 30317
  otlp-http:
    enabled: true
    servicePort: 4318
    nodePort: 30318
  metrics:
    enabled: true
    containerPort: 8888
    servicePort: 8888
    protocol: TCP
  health-check:
    enabled: true
    containerPort: 13133
    servicePort: 13133
    protocol: TCP
